<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MpsMes.Core</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
</Project>
