CREATE DATABASE IF NOT EXISTS mpsmesdb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'mes_user1'@'localhost'
  IDENTIFIED BY 'mes1234!';

ALTER USER 'mes_user1'@'localhost'
  IDENTIFIED BY 'mes1234!';

GRANT ALL PRIVILEGES ON mpsmesdb.* TO 'mes_user1'@'localhost';
FLUSH PRIVILEGES;

USE mpsmesdb;

CREATE TABLE IF NOT EXISTS TB_PRODUCTION_HISTORY (
  SEQ BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COMPLETED_AT DATETIME NOT NULL,
  CYCLE_TIME_SEC DECIMAL(10,2) NULL,
  METAL_QTY INT NOT NULL DEFAULT 0,
  NON_METAL_QTY INT NOT NULL DEFAULT 0,
  VISION_RESULT VARCHAR(10) NULL,
  DEFECT_TYPE VARCHAR(100) NULL,
  CONFIDENCE DECIMAL(8,3) NULL,
  SHIFT_CODE VARCHAR(20) NULL,
  INDEX IX_PROD_COMPLETED_AT (COMPLETED_AT),
  INDEX IX_PROD_RESULT (VISION_RESULT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TB_VISION_INSPECTION (
  SEQ BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  INSPECTED_AT DATETIME NOT NULL,
  RESULT VARCHAR(10) NOT NULL,
  DEFECT_TYPE VARCHAR(100) NULL,
  CONFIDENCE DECIMAL(8,3) NULL,
  IMAGE_PATH VARCHAR(500) NULL,
  METAL_YN CHAR(1) NOT NULL DEFAULT 'N',
  PROD_SEQ BIGINT NULL,
  INDEX IX_VISION_INSPECTED_AT (INSPECTED_AT),
  INDEX IX_VISION_RESULT (RESULT),
  INDEX IX_VISION_PROD_SEQ (PROD_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TB_EVENT_LOG (
  SEQ BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EVENT_AT DATETIME NOT NULL,
  EVENT_TYPE VARCHAR(30) NOT NULL,
  EVENT_CODE VARCHAR(100) NULL,
  MESSAGE TEXT NOT NULL,
  SOURCE VARCHAR(100) NULL,
  INDEX IX_EVENT_AT (EVENT_AT),
  INDEX IX_EVENT_TYPE (EVENT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TB_PLC_SNAPSHOT (
  SEQ BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SNAP_AT DATETIME NOT NULL,
  D10_NON_METAL INT NOT NULL DEFAULT 0,
  D11_METAL INT NOT NULL DEFAULT 0,
  D2000_SERVO_POS INT NOT NULL DEFAULT 0,
  D2005_SERVO_STS INT NOT NULL DEFAULT 0,
  MODE_D0 INT NOT NULL DEFAULT 0,
  SIGNAL_D1 INT NOT NULL DEFAULT 0,
  INDEX IX_PLC_SNAP_AT (SNAP_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
